### ISSUE TITLE
Duplicate Chapters / Novels being added after automatic scan

### ISSUE THREAD

**Issue by motodrew** [Kareadita/Kavita#1576]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
After Comics, Manga, or Light Novels are added to the file system. The automatic scan will run but will create duplicates for several of the items.

**To Reproduce**
1. Running nightly 0.5.6.24
2. Add new files to a folder on NAS. These are added into a folder structure that looks like comics/Manga/The Beginning After the End with all of the files just in that one folder
3. Wait for Scanner to automatically run and finish
4. Clicking on series from Recently Updated Series look at the latest ones and you will see duplicates

**Expected behavior**
No duplicate records should be created during a scan

**Screenshots**
![image](https://user-images.githubusercontent.com/4896141/194685920-4b06d94b-efa4-4750-b4f8-7e875cf25c65.png)
![image](https://user-images.githubusercontent.com/4896141/194685942-b3861b46-f59a-49e3-9732-f27e9c531476.png)
![image](https://user-images.githubusercontent.com/4896141/194685950-30b2b695-0138-4ef3-933b-d736af1bb945.png)
![image](https://user-images.githubusercontent.com/4896141/194685965-b2a44edb-7388-46ec-bb6c-462b5e1b2e61.png)

**Desktop (please complete the following information):**
 - OS: Docker -- using Unraid
 - Browser: chrome
 - Version [e.g. 22] (can be found on Server Settings -> System tab): 0.5.6.24

**Additional context**
If possible having a way of deleting these duplicates would be helpful as well from the database, not the actual files, either singly or en-masse.

**Comment by majora2007** [comment]
Do you have folder watching enabled? I saw this happen and fixed it in a local branch but it was due to folder watching rather than just a nightly scan.

**Comment by motodrew** [comment]
Yes I do, I have since turned it off as this was happening anytime new files were being added, but for testing happy to turn it on again

**Comment by majora2007** [comment]
I believe this to be an bug in the scan loop. I have it fixed in https://github.com/Kareadita/Kavita/pull/1573/, which I'm doing extended testing on. Once I merge that in, I'd recommend you to check out the new release and test this (with or without folder testing).

You will have to delete the series before hand. I should have this build out today after a final round of testing.

**Comment by majora2007** [comment]
Hi, with v0.5.6.25 out, could you please retest if you're getting this issue and if no longer getting, close the issue?

**Comment by motodrew** [comment]
Looks to be a bit slower but everything is working great!

**Comment by motodrew** [comment]
Actually sorry looks like this is still an issue. Before it was always happening at the later chapters that were added but now it is on the earlier ones.

**Comment by motodrew** [comment]
Actually sorry looks like this is still an issue. Before it was always happening at the later chapters that were added but now it is on the earlier ones.

**Comment by majora2007** [comment]
Can you delete the series then rescan? Or check your logs, there is enhanced logging to tell you of corruption and steps to take. 

Use [ScannerService] for searching

**Comment by motodrew** [comment]
Yuppers when I ran the manual scan after deleting them they worked correctly. As for searching for Corruption do you want me to delete the series and move the out of the folder. Then re-add the series with the Folder Watching on?

**Comment by majora2007** [comment]
Yes, if you see the corrupted error message, you just delete the series in Kavita only and the next rescan should fix everything up. No need to muck around with the actual files.

**Comment by motodrew** [comment]
Gotcha, I am seeing the `Kavita found corrupted volume entries on`... messages in my logs and deleting the series and running a manual scan works for cleaning things up.

Would you like me to keep this issue open as it seems like having the Folder Watching turned on still creates these duplicate entries?

**Comment by majora2007** [comment]
No, let's close this and open a new one up, since it's a separate issue.
