### ISSUE TITLE
Removing a book from a reading list resets manual ordering

### ISSUE THREAD

**Issue by YellowWords** [Kareadita/Kavita#1722]
**Describe the bug**
When a book is removed from a reading list, any manual order added to the list get reset and the list is sorted in order of when the book was added to the list.

This can be very frustrating on a long reading list. For example I have a reading list with all the fiction books I want to read that has 97 books on it, manually reordering such a long list constantly is a chore.

**To Reproduce**
1. Make a reading list and add some books to it.
2. Manually reorder the books on the list with order number or drag-and-drop.
3. Remove one book from the list by clicking the x button.

**Expected behavior**
I expect the books below the one that is removed to be shifted up one step, but no other changes to the ordering.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2
 - Browser LibreWolf
 - Version 0.6.1.0

**Comment by majora2007** [comment]
The expected is how it is designed actually. When removing an item, the other items afterwards just change their order to current - 1, so that they shift up essentially. 

Let me look into this, last release testing it was working as expected.

**Comment by majora2007** [comment]
I just confirmed that the reading list is working as intended. Reordering is natural and removing any item is clearing said item and all under move up to replace that item's order.

**Comment by YellowWords** [comment]
> I just confirmed that the reading list is working as intended. Reordering is natural and removing any item is clearing said item and all under move up to replace that item's order.

Hmm, okay, that's too bad. In my local setup the lists still reorder themselves every time I remove a book. I'll put in some work on my end and see if I can fix this error or make it more reproducible.

**Comment by majora2007** [comment]
If you can get me detailed steps to reproduce, I'm sure I'll be able to reproduce it. It may also be there was a bug in v0.6.1.0 that I've already fixed in nightly for the next stable release. Feel free to re-open the bug if you can update the reproduction steps.

**Comment by YellowWords** [comment]
So when I first reported this issue I was using [Linux Install](https://wiki.kavitareader.com/en/install/linux-install). I tried switching to a fresh [docker-compose install](https://wiki.kavitareader.com/en/install/docker-install) using `nightly`. However I can still reproduce this issue here. The only things is that you just need to reload the page afterwards to see the manual order has been removed.

Here's the docker-compose I'm using, lightly edited to remove some personal information:
```
version: '3.9'
services:
    kavita:
        image: kizaing/kavita:nightly
        container_name: kavita
        volumes:
            - /media/***/glacier/media/data/books:/books
            - /home/***/Kavita:/kavita/config
        environment:
            - TZ=***
        ports:
            - "9999:5000"
        restart: unless-stopped
```

Could you try this and see if it helps you reproduce the issue?
1. Install something similar to the above docker compose.
2. Add 3 eBooks to a new reading list.
3. Drag the last eBook in the list to the front of the list.
4. Remove the number 2 book using the Remove button.
5. Reload the page - Is the book you reordered still first, or last? To me this results in the reordered book going back to last position so the order resets.

If this doesn't work I'm really at a loss here. :-/

**Comment by majora2007** [comment]
can you be a bit more explicit in your instructions and what your seeing? 3 books, can you show chapter 1, 2, 3. Then remove chapter 2 which is in position 2, expected order after page refresh is: Chapter 1 and Chapter 3, actual: Chapter 3 Chapter 1

I need it to be very clear to ensure we are thinking the same thing.

**Comment by YellowWords** [comment]
Start with a new reading list that looks like this:

1. Series A
2. Series B
3. Series C

Drag and drop book C to the top of the list so it looks like this:
1. Series C
2. Series A
3. Series B

Now remove Series A and reload the page:

Expected result:
1. Series C
2. Series B

Actual result:
1. Series B
2. Series C

**Comment by majora2007** [comment]
Okay was able to reproduce sometimes. Ill take a look.

**Comment by YellowWords** [comment]
I tested the fix on nightly and confirmed it works now! I donated some bucks to Kavita by way of thanks.

**Comment by majora2007** [comment]
Thanks, I saw that. I really appreciate the donation :)
