### ISSUE TITLE
unable to scroll in menus when in landscape mode on my tablet.

### ISSUE THREAD

**Issue by rix8675** [Kareadita/Kavita#3294]
### What happened?

when using kavita on my tablet if i'm navigating the menus when looking through the series/chapter/volumes  sections in the menus and using landscape mode i cannot scroll down or up. if i switch to portrait it works just fine then it gets weirder by working in landscape when actually reading the chapters/books.
so 
-works in landscape while reading the chapter/book.
-does not work in landscape when navigating the  menus.
-can still select and interact with things in the menus other than scrolling in landscape.
-everything works flawless in portrait mode.
so basically i just can't scroll when in landscape mode in the menus on my samsung galaxy note 10.1 201
it's an older device so i'm not too worried if this doesn't get resolved as i can just switch to portrait and everything works just fine.

### What did you expect?

to be able to scroll while in landscape in the menus.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Chrome

### Additional Notes

this is being hosted on windows using docker using jvmilazz0/kavita latest , as for the logs it doesn't say anything new when switching from portrait to horizontal.

**Comment by majora2007** [comment]
I just experienced this yesterday myself and was shocked because I could have sworn we fixed this before the v0.8.4 release.

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by majora2007** [comment]
For reference, clicking anywhere on the page will fix this.

**Comment by majora2007** [comment]
Okay I can't reproduce this anymore. I think it was a one time thing and after I tapped anywhere on the screen, it worked from then onwards. Can you reliably reproduce this?

**Comment by rix8675** [comment]
on version 0.8.3.24 it still happens but tapping on the screen again now fixes it.

**Comment by majora2007** [comment]
@rix8675 It fixes it one time or permanently?

**Comment by rix8675** [comment]
- every time i reload the home page it won't initially scroll still, everywhere else works just fine now. i can click on open space and then Scrolling works just like normal.
- i've also tried giving it 2 3 minutes just in case it was some loading issue or something, but this doesn't seem to be the issue.

**Comment by majora2007** [comment]
@therobbiedavis 

Hmm the problem is we can't seem to reproduce the issue. I just tried again on my mobile and it just works. I only experienced this during testing of the UX overhaul (pre-release) and once after I updated and loaded the new UI code on my tablet.

**Comment by rix8675** [comment]
it seems to be only an issue on my samsung tablet now which isn't a problem since all i gotta do is tap on a blank space now and it works like normal.
- it is also working as expected on all my other devices at this time.

**Comment by majora2007** [comment]
Oh interesting. So for now, we will consider it low priority. Can you provide information about your model/chrome version/dimensions for future reference.

**Comment by rix8675** [comment]
Brand: samsung
type: Galaxy note 10.1 201
screen size: 10.1 Inch
model: SM-P607T
android version: 5.1.1
Screen resolution: 2560 x 1600 pixels, 16:10 
Chrome Version: 95.0.4638.74
gsmarena link: https://www.gsmarena.com/samsung_galaxy_note_10_1_(2014)-5677.php  (hopefully this isn't breaking a rule if so lemme know and i'll remove it)
it's an old tablet and there is no new updates for anything even on the google play store.

**Comment by majora2007** [comment]
Thanks. I'll move this to our backlog for now. The UX overhaul isn't complete even as of now, so maybe the further enhancements will fix whatever the underlying issue is.
