### ISSUE TITLE
Scanner removing series that exist when the files are there

### ISSUE THREAD

**Issue by thezak48** [Kareadita/Kavita#3476]
### What happened?

Every time the library is scaned it removes and readd's the same series. This was identified on discord to be an bug that happens when there are multiple folders for the library

### What did you expect?

It not to remove and readd series

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.4.2 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by xxwhirlpool** [comment]
same problem. i have large libraries and the re-add subsequently removes reading progress & list additions. no pressure but i hope this is fixed in the next version!

**Comment by majora2007** [comment]
Hi all, looking into this now. Trying to figure out when this triggers as I have multiple roots and haven't seen this. 

Can anyone show me how to reproduce it in this format? 

```
[
    "Root 1/Antarctic Press/Plush/Plush v01.cbz",
    "Root 1/Antarctic Press/Plush/Plush v02.cbz",
    "Root 2/Accel/Accel v01.cbz",
]
```

Edit: I can't reproduce this

**Comment by versita** [comment]
I'm running it in a Docker container and have 2 media directories. Currently running 0.8.4.2

The root directories look something like this:
```
[
  "/data/Manga/GE Good Ending/ch001.cbz"
  "/data/Manga/0.2秒の物語/0.2秒の物語 Vol.1.cbz"
  "/data/Comics"
  "/data/One shots"
  "/storage/manga/Claymore/Claymore - c001-004 (v01).zip"
  "/storage/manga/Magus of the Library (Digital)/Magus of the Library v01 (2019) (Digital).cbz"
]
```
There is no overlap in series between any directories. Each series is in its own subdirectory. I have tested a library with just those 4 series in the directories and still get the same issue. 

If I add each of the directories in `/data` individually to the library, then the series in `/data/One shots` alternates between being added and removed with each scan while the `/data/Manga` and `/data/Comics` series remain in the library. If I just add the whole `/data` directory to the library then everything seems to be okay.

If I add `/data/Manga`, `/data/One shots`, and `/storage/manga` to a library, then all series in `/data/One shots` and `/storage/manga` will alternate between being added and removed.

With only `/data/One shots` and `/storage/manga` in the library, nothing is removed on scan.

Here is some relevant log output:

```
[Kavita] [2025-02-16 11:58:52.749 -05:00  81] [Information] API.Services.TaskScheduler Enqueuing library scan for: 14
[Kavita] [2025-02-16 11:58:52.749 -05:00  81] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/library/scan?libraryId=14&force=false responded 200 in 0.8894 ms
[Kavita] [2025-02-16 11:58:52.773 -05:00  81] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Test
[Kavita] [2025-02-16 11:58:52.773 -05:00  81] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library Test Step 1: Scan & Parse Files
[Kavita] [2025-02-16 11:58:52.774 -05:00  81] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library Test Step 1.A: Process 2 folders
[Kavita] [2025-02-16 11:58:52.774 -05:00  81] [Debug] API.Services.Tasks.ScannerService 	[ScannerService] Library Test Step 1.B: Scan files in /storage/manga
[Kavita] [2025-02-16 11:58:52.778 -05:00  81] [Debug] API.Services.Tasks.ScannerService [ScannerService] Step 1.C Found 28 directories to process for /storage/manga
[Kavita] [2025-02-16 11:58:52.791 -05:00  81] [Debug] API.Services.Tasks.ScannerService [ProcessFiles] Skipping /storage/manga/Claymore as it hasn't changed since last scan
[27 more entries for skipping directories]
[Kavita] [2025-02-16 11:58:52.795 -05:00  81] [Debug] API.Services.Tasks.ScannerService 	[ScannerService] Library Test Step 1.C: Process files in /storage/manga
[Kavita] [2025-02-16 11:58:52.796 -05:00  81] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /storage/manga/Claymore as it hasn't changed
[27 more entries for skipped file scan]
[Kavita] [2025-02-16 11:58:52.796 -05:00  81] [Debug] API.Services.Tasks.ScannerService 	[ScannerService] Library Test Step 1.D: Merge any localized series with series /storage/manga
[Kavita] [2025-02-16 11:58:52.796 -05:00  81] [Debug] API.Services.Tasks.ScannerService 	[ScannerService] Library Test Step 1.E: Group all parsed data into logical Series
[Kavita] [2025-02-16 11:58:52.796 -05:00  81] [Debug] API.Services.Tasks.ScannerService 	[ScannerService] Library Test Step 1.F: Generate Sort Order for Series and Finalize
[Kavita] [2025-02-16 11:58:52.796 -05:00  81] [Debug] API.Services.Tasks.ScannerService 	[ScannerService] Library Test Step 1.B: Scan files in /data/Manga
[Kavita] [2025-02-16 11:58:52.833 -05:00  81] [Debug] API.Services.Tasks.ScannerService [ScannerService] Step 1.C Found 21 directories to process for /data/Manga
[Kavita] [2025-02-16 11:58:52.857 -05:00  81] [Debug] API.Services.Tasks.ScannerService [ProcessFiles] Skipping /data/Manga/GE Good Ending as it hasn't changed since last scan
[20 more entries for skipping directories]
[Kavita] [2025-02-16 11:58:52.862 -05:00  81] [Debug] API.Services.Tasks.ScannerService 	[ScannerService] Library Test Step 1.C: Process files in /data/Manga
[Kavita] [2025-02-16 11:58:53.295 -05:00  81] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/Manga/GE Good Ending as it hasn't changed
[20 more entries for skipped file scan]
[Kavita] [2025-02-16 11:58:53.295 -05:00  81] [Debug] API.Services.Tasks.ScannerService 	[ScannerService] Library Test Step 1.D: Merge any localized series with series /data/Manga
[Kavita] [2025-02-16 11:58:53.295 -05:00  81] [Debug] API.Services.Tasks.ScannerService 	[ScannerService] Library Test Step 1.E: Group all parsed data into logical Series
[Kavita] [2025-02-16 11:58:53.295 -05:00  81] [Debug] API.Services.Tasks.ScannerService 	[ScannerService] Library Test Step 1.F: Generate Sort Order for Series and Finalize
[Kavita] [2025-02-16 11:58:53.295 -05:00  81] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library Test Step 2: Process and Update Database
[Kavita] [2025-02-16 11:58:53.296 -05:00  81] [Information] API.Services.Tasks.ScannerService [ScannerService] Attempting to pre-save all Genres
[Kavita] [2025-02-16 11:58:53.296 -05:00  81] [Information] API.Services.Tasks.ScannerService [ScannerService] Attempting to pre-save all Tags
[Kavita] [2025-02-16 11:58:53.337 -05:00  81] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished file scan in 522 milliseconds. Updating database
[Kavita] [2025-02-16 11:58:53.337 -05:00  81] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library Test Step 3: Save Library
[Kavita] [2025-02-16 11:58:53.340 -05:00  81] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished library scan of 30 files and 19 series in 590 milliseconds for Test
[Kavita] [2025-02-16 11:58:53.340 -05:00  81] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library Test Step 5: Remove Deleted Series
[Kavita] [2025-02-16 11:58:53.340 -05:00  81] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing series that were not found during the scan
[Kavita] [2025-02-16 11:58:53.341 -05:00  81] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 28 series to remove: [list of series that were in the /storage/manga directory]
[Kavita] [2025-02-16 11:58:53.365 -05:00  81] [Debug] API.Services.Tasks.ScannerService [ScannerService] Series removal process completed
[Kavita] [2025-02-16 11:58:53.378 -05:00  37] [Information] API.Services.Tasks.CleanupService Performing cleanup of Cache directories
[Kavita] [2025-02-16 11:58:53.378 -05:00  37] [Information] API.Services.Tasks.CleanupService Cache directory purged
[Kavita] [2025-02-16 11:58:53.599 -05:00  56] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/series/v2 responded 200 in 1.8784 ms
```

**Comment by majora2007** [comment]
I wasn't able to grasp what @versita mentioned exactly, but I did create a unit test that reproduces there is some issue with adding and removing library root folders then scanning. 

Unfortunately, it's too close to the next Stable release to address this, so I will push to v0.8.6. 

Also @versita you should drop by the discord. You can likely have a much better setup than what I'm taking away from your comment.
